#!/bin/sh

sxhkd & 
# Polybar
$HOME/dotfiles/bspwm/launchpolybar.sh &
# Compton
killall -q compton; compton --config ~/.config/compton.conf &
# Dunst
killall -q notify-osd
dunst -config ~/.config/dunst/dunstrc &
# Language
setxkbmap -model pc105 -layout us,ru -option grp:win_space_toggle &
# XWINWRAP
xwinwrap -g 1920x1080 -ov -ni -s -nf --gifview -w WID ~/wallpaper.gif -a &
# Startup
alacritty &
emacs26 &
bspc desktop -f ^1


bspc monitor -d Desktop Web Terminal Editors 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# Mouse tweaks
bspc config focus_follows_pointer true

#RULES#
#WEB##
bspc rule -a Firefox desktop=^2 follow=on
bspc rule -a Chromium desktop=^2 follow=on
bspc rule -a telegram-desktop desktop=^2 follow=on
bspc rule -a discord desktop=^2
#TERMINALS##
bspc rule -a Alacritty desktop=^3 follow=on
bspc rule -a xterm desktop=^3 follow=on
#EDITORS##
bspc rule -a Emacs desktop=^4 follow=on
bspc rule -a vim desktop=^4 follow=on
bpsc rule -a nvim desktop=^4 follow=on
#FM##
bspc rule -a nautilus desktop=^5 follow=on
bspc rule -a Ranger desktop=^5 state=floating follow=on
