#!/bin/sh
# XWINWRAP and bind-programm
sxhkd &
#bash xwinwrap -g 1920x1080 -ov -ni -s -nf --gifview -w WID ~/wallpaper.gif -a &
feh --bg-scale ~/wallpaper.jpg &
# Polybar
$HOME/dotfiles/bspwm/launchpolybar.sh &
# Compton
killall -q compton; compton --config ~/.config/compton.conf &
# Dunst
killall -q notify-osd &
dunst -config ~/.config/dunst/dunstrc &
# Language
setxkbmap -model pc105 -layout us,ru -option grp:win_space_toggle &
# Startup
alacritty &
emacs26 &
bspc desktop -f ^1 &

bspc monitor -d Desktop Web Terminal Editors

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# Mouse tweaks
bspc config focus_follows_pointer true

#RULES#
#FM##
bspc rule -a Nautilus desktop=^1
bspc rule -a :"ranger" desktop=^1 state=floating follow=on
#WEB##
bspc rule -a Firefox desktop=^2
bspc rule -a Chromium desktop=^2
bspc rule -a telegram-desktop desktop=^2 follow=on
bspc rule -a discord desktop=^2
#TERMINALS##
bspc rule -a Alacritty desktop=^3 follow=on
bspc rule -a xterm desktop=^3 follow=on
#EDITORS##
bspc rule -a Emacs desktop=^4 follow=on state=tiled
bspc rule -a vim desktop=^4 follow=on
bpsc rule -a nvim desktop=^4 follow=on
