alias l="ls -la"
alias Dd='~/dotfiles'
alias em='emacs26'
alias fr='firefox'
alias es='pkill save_your_eyes.sh'
alias ns='~/dotfiles/scripts/notes.sh new'
alias sns='~/dotfiles/scripts/notes.sh show'
alias dt='trash' # Delete to the trash
alias tl='trash-list' # Trash-list
alias rt='restore-trash' #Restore Trash
