#!/bin/sh

case $BLOCK_BUTTON in
    1) pavucontrol ;; 
    2) amixer sset Master toggle > /dev/null 2>/dev/null ;;
    3) notify-send "Громкость" "LC - открыть pavucontrol\nRC - открыть это сообщение" ;;
    4) amixer sset Master 5%+ >/dev/null 2>/dev/null ;;
	5) amixer sset Master 5%- >/dev/null 2>/dev/null ;;

esac; 

echo "<span bgcolor='#e84393' color='#f3f3f3'> VOL:`amixer -D pulse sget Master | grep 'Left:' | grep '\[off\]' > /dev/null && echo off || amixer -D pulse sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }'` </span>"
